### ISSUE TITLE
Problem Aksara.py in Windows

### ISSUE THREAD

**Issue by mukhlizarnirwans** [ir-nlp-csui/aksara#1]
![WhatsApp Image 2021-10-14 at 12 51 15](https://user-images.githubusercontent.com/72326401/137446013-64eaa6de-2686-48b1-9028-87742ff7a5fe.jpeg)
I try to run aksara.py on windows, and I have an issue 'charmap codec can't decode byte 0x9d in position...'
I have followed the installation instruction, such as installed foma ( using this [guide](https://blogs.cornell.edu/finitestatecompling/2016/08/24/installing-foma/) ), and installed the requirements.txt.

I also searching for this error, and have this [answer](https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character), could someone help me to fix this problem?

**Comment by mridho2828** [comment]
Hello @mukhlizarnirwans thank you for informing the problem. I have checked the default encoding of my machine and it shows that the default encoding is `UTF-8`. Since Aksara works on my machine then it should have no problem on another machine that also uses `UTF-8` encoding. So, I guess the problem is that your machine somehow doesn't use `UTF-8` as the default encoding.  However, I have changed the code so that now it will always use `UTF-8`. You can try it now and please let me know should you have further issues.

**Comment by mukhlizarnirwans** [comment]
![Capture](https://user-images.githubusercontent.com/72326401/140606884-b50d071f-7206-44a3-8843-c355fa0dcb0d.JPG)
Saya sudah mencoba update terbaru dari aksara, namun saya masih menemukan error seperti di atas. saya sudah mencari solusi dari error 'PermissionError: [Errno 13] Permission denied' dan menemukan bahwa error tersebut karena saya tidak memiliki akses karena bukan pemilik dari folder/file tersebut, untuk mengatasinya saya coba menggunakan 
"takeown"  agar saya memiliki akses. tapi error yang sama tetap muncul, saya juga menemukan bahwa  file yang dirujuk errorpun berubah-ubah seperti "... \\Temp\\tmpyxpoei9q", "...\\Temp\\tmpwy42uyd1", "...\\Temp\\tmpntcwpnh9" dll. Apakah ada saran untuk permasalahan ini ?
